### ISSUE TITLE
Dataset landing page "tabs" are not deep-linkable

### ISSUE THREAD

**Issue by mih** [psychoinformatics-de/sfb1451-projects-catalog#33]
For #32 I wanted to point to the BIDS metadata tab. However, I found no way to do so, but had to resort to verbal navigation instruction.

We could add an explicit `<url>?tab=bids` type URL extension that is readily available for C&P.

**Comment by jsheunis** [comment]
This should have been addressed with https://github.com/datalad/datalad-catalog/pull/295, but I have tested this in the sfb1451 catalog and indeed this doesn't seem to work.

https://psychoinformatics-de.github.io/sfb1451-projects-catalog/#/dataset/a808f9e1-d638-4771-ae4c-ff21da29151a/272e2844cd7c58dda8dfe288e7831ad2fa9c34b6/bids

 I will investigate.

**Comment by jsheunis** [comment]
A fix for this is now in `datalad-catalog` main.

**Comment by jsheunis** [comment]
A remaining issue has been highlighted by here: https://github.com/datalad/datalad-catalog/issues/391

**Comment by jsheunis** [comment]
I've worked further on the remaining issue (letting the tab parameter in the URL mirror the actual tab being selected, continuously), but haven't found a resolution yet. From the perspective of `datalad-catalog`, this is part of a broader challenge of having intuitive and consistent navigation behaviour, and this requires more thought and work to get it right. This won't happen soon (enough) for the goal of getting a polished sfb catalog out. So I suggest we close this issue, or at least tag it as "won't fix" (with respect to the tab-URL mirroring part).

**Comment by mih** [comment]
Just recording that this is still not possible in the current draft.

**Comment by jsheunis** [comment]
I see the following upon page inspection:

```
vue.2.6.14.min.js:6 ReferenceError: tabs is not defined
    at a.setCorrectTab (app_component_dataset.js:574:15)
    at a.created (app_component_dataset.js:865:16)
```

I think this error was introduced with the last patch from datalad catalog. will fix it.
